In [1]:
import pandas as pd
import numpy as np

In [ ]:
#importing dataset
dt=pd.read_csv("data/diabities.csv")
dt.head(10)

,Unnamed: 0,Pregnancies,Glucose,blood pressure,skin thickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,NaN,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,NaN,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,NaN,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,NaN,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,NaN,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
5,NaN,5.0,116.0,74.0,0.0,0.0,25.6,0.201,30.0,0.0
6,NaN,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
7,NaN,10.0,115.0,0.0,0.0,0.0,35.3,0.134,29.0,0.0
8,NaN,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
9,NaN,8.0,125.0,96.0,0.0,0.0,0.0,0.232,54.0,1.0

In [23]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                0 non-null      float64
 1   Pregnancies               768 non-null    float64
 2   Glucose                   768 non-null    float64
 3   blood pressure            768 non-null    float64
 4   skin thickness            768 non-null    float64
 5   Insulin                   768 non-null    float64
 6   BMI                       768 non-null    float64
 7   DiabetesPedigreeFunction  768 non-null    float64
 8   Age                       768 non-null    float64
 9   Outcome                   768 non-null    float64
dtypes: float64(10)
memory usage: 60.2 KB

In [24]:
#help(dt.pop)
dt.pop('Unnamed: 0')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
764   NaN
765   NaN
766   NaN
767   NaN
768   NaN
Name: Unnamed: 0, Length: 769, dtype: float64

In [25]:
dt

,Pregnancies,Glucose,blood pressure,skin thickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0
768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#help(dt.sum)
dt.isnull().sum()

Pregnancies                 1
Glucose                     1
blood pressure              1
skin thickness              1
Insulin                     1
BMI                         1
DiabetesPedigreeFunction    1
Age                         1
Outcome                     1
dtype: int64

In [26]:
#Since there are null values we have to remove them
#using dt.drop()
dt=dt.drop([768],axis=0)
dt

,Pregnancies,Glucose,blood pressure,skin thickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0

In [27]:
dt.isnull().sum()
#there is no more null elements

Pregnancies                 0
Glucose                     0
blood pressure              0
skin thickness              0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [32]:
X = dt.iloc[:,:-1]
y = dt.iloc[:,-1]

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 25, random_state = 0)

In [34]:
# using Random forrest Classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 6, criterion = 'entropy', random_state = 0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score
acc_rfc = accuracy_score(y_pred,y_test)*100
print("Accuracy:",acc_rfc)

Accuracy: 88.0

In [38]:
#using logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, r2_score,classification_report
logreg = LogisticRegression(solver = 'lbfgs', max_iter = 1000)
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)
acc_logreg1 = accuracy_score(y_pred, y_test)*100
print("Accuracy:", acc_logreg1)

Accuracy: 96.0

In [41]:
#using K-NN Classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 2)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
acc_knn = accuracy_score(y_pred, y_test)*100
print("Accuracy:", acc_knn)

Accuracy: 80.0